### ISSUE TITLE
master refers to non-existent htslib commit

### ISSUE THREAD

**Issue by sambrightman** [walaj/SeqLib#11]
```
[sam@Sams-MacBook-Pro SeqLib (master *=)]$ git diff
diff --git htslib htslib
index 5163833..0f298ce 160000
--- htslib
+++ htslib
@@ -1 +1 @@
-Subproject commit 5163833ede355f8c2a6788780c55d7598279e767
+Subproject commit 0f298ce22c5c825c506129bf242348a31630c382
[sam@Sams-MacBook-Pro SeqLib (master *=)]$ git submodule update --init --recursive
error: no such remote ref 5163833ede355f8c2a6788780c55d7598279e767
Fetched in submodule path 'htslib', but it did not contain 5163833ede355f8c2a6788780c55d7598279e767. Direct fetching of that commit failed.
```

Is it even necessary to refer to your fork instead of upstream htslib? I don't immediately see any differences.

**Comment by walaj** [comment]
I see that my .gitmodules wasn't pointing to a specific branch of htslib, so perhaps that was causing a problem. I updated to have it point to the "develop" branch of my fork, which is synced with the upstream version. Let me know if still an issue.

I forked htslib because I wanted to point to a feature that wasn't in the main htslib yet, as some users wanted Google cloud access from htslib.
